"""Planner engines - objective DAG, scheduler, recommendation solver.

Mechanism, not data. Nothing in this package knows a character name, a material
id or a quantity: costs, gates and candidates all arrive from the caller. The
one exception is the ascension level cap table in `objectives`, which is a
structural constant pinned by docs/SPEC_SCAFFOLD.md rather than farmable data.
"""
from __future__ import annotations

from engines.objectives import (
    ASCENSION_LEVEL_CAPS,
    MAX_ASCENSION_PHASE,
    MAX_TALENT_LEVEL,
    MIN_TALENT_LEVEL,
    TALENT_MAX_ASCENSION,
    TALENT_MIN_ASCENSION,
    CyclicObjectiveError,
    DuplicateObjectiveError,
    NodeCost,
    ObjectiveGraph,
    ObjectiveGraphError,
    UnknownDependencyError,
    UnknownObjectiveError,
    build_graph,
    character_ascension_id,
    character_level_id,
    critical_path,
    expand_character_goal,
    min_ascension_for_talent,
    required_ascension_for_level,
    talent_id,
    topological_order,
    unmet_prerequisites,
    weapon_ascension_id,
    weapon_level_id,
)
from engines.recommend import (
    WEIGHT_COVERAGE_GAP,
    WEIGHT_NEAR_COMPLETION,
    WEIGHT_UNBLOCKS,
    WEIGHT_VALUE_PER_RESIN,
    Candidate,
    ScoredAxis,
    coverage_gaps,
    recommend,
    score_candidate,
)
from engines.scheduler import (
    DEFAULT_HORIZON_DAYS,
    DEFAULT_RESIN_PER_DAY,
    MAX_SCHEDULE_ITERATIONS,
    WEEKLY_WINDOW_DAYS,
    ScheduleOutcome,
    UnknownScheduleNodeError,
    estimated_days,
    naive_days,
    plan,
    schedule,
    solve,
)

__all__ = [
    "ASCENSION_LEVEL_CAPS",
    "DEFAULT_HORIZON_DAYS",
    "DEFAULT_RESIN_PER_DAY",
    "MAX_ASCENSION_PHASE",
    "MAX_SCHEDULE_ITERATIONS",
    "MAX_TALENT_LEVEL",
    "MIN_TALENT_LEVEL",
    "TALENT_MAX_ASCENSION",
    "TALENT_MIN_ASCENSION",
    "WEEKLY_WINDOW_DAYS",
    "WEIGHT_COVERAGE_GAP",
    "WEIGHT_NEAR_COMPLETION",
    "WEIGHT_UNBLOCKS",
    "WEIGHT_VALUE_PER_RESIN",
    "Candidate",
    "CyclicObjectiveError",
    "DuplicateObjectiveError",
    "NodeCost",
    "ObjectiveGraph",
    "ObjectiveGraphError",
    "ScheduleOutcome",
    "ScoredAxis",
    "UnknownDependencyError",
    "UnknownObjectiveError",
    "UnknownScheduleNodeError",
    "build_graph",
    "character_ascension_id",
    "character_level_id",
    "coverage_gaps",
    "critical_path",
    "estimated_days",
    "expand_character_goal",
    "min_ascension_for_talent",
    "naive_days",
    "plan",
    "recommend",
    "required_ascension_for_level",
    "schedule",
    "score_candidate",
    "solve",
    "talent_id",
    "topological_order",
    "unmet_prerequisites",
    "weapon_ascension_id",
    "weapon_level_id",
]
